services:
  nextjs:
    container_name: next-pwa-app
    build: .
    ports:
      - "3000:3000"
    restart: always # 🔥 Auto-start container saat reboot
    networks:
      - appnet

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - nextjs
    restart: always # 🔥 Ini juga auto-start saat boot
    networks:
      - appnet

networks:
  appnet:
