import "~/styles/globals.css";
import { type Metadata } from "next";
import { TRPCReactProvider } from "~/trpc/react";
import { InstallPrompt } from "~/components/InstallPrompt"; // arahkan sesuai path

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#0f172a" />
        <link rel="icon" href="/icons/icon-128x128.png" />
      </head>
      <body className="font-mono">
        <TRPCReactProvider>
          <InstallPrompt />
        </TRPCReactProvider>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
